const hangjungdong: any = {
  // 시/도, 서울시만 적용(1개 시)
  sido: [{ sidoNum: '1', sidoName: '서울특별시' }],

  // 시/군/구, 서울시 자치구 25개(강남구~중랑구)
  sigungu: [
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '1',
      sigunguName: '강남구',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '2',
      sigunguName: '강동구',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '3',
      sigunguName: '강북구',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '4',
      sigunguName: '강서구',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '5',
      sigunguName: '관악구',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '6',
      sigunguName: '광진구',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '7',
      sigunguName: '구로구',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '8',
      sigunguName: '금천구',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '9',
      sigunguName: '노원구',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '10',
      sigunguName: '도봉구',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '11',
      sigunguName: '동대문구',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '12',
      sigunguName: '동작구',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '13',
      sigunguName: '마포구',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '14',
      sigunguName: '서대문구',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '15',
      sigunguName: '서초구',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '16',
      sigunguName: '성동구',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '17',
      sigunguName: '성북구',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '18',
      sigunguName: '송파구',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '19',
      sigunguName: '양천구',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '20',
      sigunguName: '영등포구',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '21',
      sigunguName: '용산구',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '22',
      sigunguName: '은평구',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '23',
      sigunguName: '종로구',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '24',
      sigunguName: '중구',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '25',
      sigunguName: '중랑구',
    },
  ],

  // 읍/면/동, 서울시 행정동 426개
  eupmyeondong: [
    //1.강남구 행정동(22)
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '1',
      sigunguName: '강남구',
      eupmyeondongNum: '1',
      eupmyeondongName: '신사동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '1',
      sigunguName: '강남구',
      eupmyeondongNum: '2',
      eupmyeondongName: '논현1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '1',
      sigunguName: '강남구',
      eupmyeondongNum: '3',
      eupmyeondongName: '논현2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '1',
      sigunguName: '강남구',
      eupmyeondongNum: '4',
      eupmyeondongName: '삼성1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '1',
      sigunguName: '강남구',
      eupmyeondongNum: '5',
      eupmyeondongName: '삼성2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '1',
      sigunguName: '강남구',
      eupmyeondongNum: '6',
      eupmyeondongName: '대치1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '1',
      sigunguName: '강남구',
      eupmyeondongNum: '7',
      eupmyeondongName: '대치2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '1',
      sigunguName: '강남구',
      eupmyeondongNum: '8',
      eupmyeondongName: '대치4동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '1',
      sigunguName: '강남구',
      eupmyeondongNum: '9',
      eupmyeondongName: '역삼1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '1',
      sigunguName: '강남구',
      eupmyeondongNum: '10',
      eupmyeondongName: '역삼2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '1',
      sigunguName: '강남구',
      eupmyeondongNum: '11',
      eupmyeondongName: '도곡1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '1',
      sigunguName: '강남구',
      eupmyeondongNum: '12',
      eupmyeondongName: '도곡2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '1',
      sigunguName: '강남구',
      eupmyeondongNum: '13',
      eupmyeondongName: '개포1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '1',
      sigunguName: '강남구',
      eupmyeondongNum: '14',
      eupmyeondongName: '개포2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '1',
      sigunguName: '강남구',
      eupmyeondongNum: '15',
      eupmyeondongName: '개포4동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '1',
      sigunguName: '강남구',
      eupmyeondongNum: '16',
      eupmyeondongName: '일원본동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '1',
      sigunguName: '강남구',
      eupmyeondongNum: '17',
      eupmyeondongName: '일원1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '1',
      sigunguName: '강남구',
      eupmyeondongNum: '18',
      eupmyeondongName: '일원2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '1',
      sigunguName: '강남구',
      eupmyeondongNum: '19',
      eupmyeondongName: '수서동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '1',
      sigunguName: '강남구',
      eupmyeondongNum: '20',
      eupmyeondongName: '세곡동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '1',
      sigunguName: '강남구',
      eupmyeondongNum: '21',
      eupmyeondongName: '압구정동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '1',
      sigunguName: '강남구',
      eupmyeondongNum: '22',
      eupmyeondongName: '청담동',
    },

    //2.서울시 강동구 행정동(19)
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '2',
      sigunguName: '강동구',
      eupmyeondongNum: '1',
      eupmyeondongName: '강일동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '2',
      sigunguName: '강동구',
      eupmyeondongNum: '2',
      eupmyeondongName: '명일1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '2',
      sigunguName: '강동구',
      eupmyeondongNum: '3',
      eupmyeondongName: '명일2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '2',
      sigunguName: '강동구',
      eupmyeondongNum: '4',
      eupmyeondongName: '고덕1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '2',
      sigunguName: '강동구',
      eupmyeondongNum: '5',
      eupmyeondongName: '고덕2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '2',
      sigunguName: '강동구',
      eupmyeondongNum: '6',
      eupmyeondongName: '암사1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '2',
      sigunguName: '강동구',
      eupmyeondongNum: '7',
      eupmyeondongName: '암사2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '2',
      sigunguName: '강동구',
      eupmyeondongNum: '8',
      eupmyeondongName: '암사3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '2',
      sigunguName: '강동구',
      eupmyeondongNum: '9',
      eupmyeondongName: '천호1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '2',
      sigunguName: '강동구',
      eupmyeondongNum: '10',
      eupmyeondongName: '천호2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '2',
      sigunguName: '강동구',
      eupmyeondongNum: '11',
      eupmyeondongName: '천호3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '2',
      sigunguName: '강동구',
      eupmyeondongNum: '12',
      eupmyeondongName: '성내1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '2',
      sigunguName: '강동구',
      eupmyeondongNum: '13',
      eupmyeondongName: '성내2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '2',
      sigunguName: '강동구',
      eupmyeondongNum: '14',
      eupmyeondongName: '성내3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '2',
      sigunguName: '강동구',
      eupmyeondongNum: '15',
      eupmyeondongName: '길동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '2',
      sigunguName: '강동구',
      eupmyeondongNum: '16',
      eupmyeondongName: '둔촌1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '2',
      sigunguName: '강동구',
      eupmyeondongNum: '17',
      eupmyeondongName: '둔촌2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '2',
      sigunguName: '강동구',
      eupmyeondongNum: '18',
      eupmyeondongName: '상일1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '2',
      sigunguName: '강동구',
      eupmyeondongNum: '19',
      eupmyeondongName: '상일2동',
    },

    //3. 서울시 강북구 행정동(13)
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '3',
      sigunguName: '강북구',
      eupmyeondongNum: '1',
      eupmyeondongName: '번1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '3',
      sigunguName: '강북구',
      eupmyeondongNum: '2',
      eupmyeondongName: '번2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '3',
      sigunguName: '강북구',
      eupmyeondongNum: '3',
      eupmyeondongName: '번3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '3',
      sigunguName: '강북구',
      eupmyeondongNum: '4',
      eupmyeondongName: '수유1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '3',
      sigunguName: '강북구',
      eupmyeondongNum: '5',
      eupmyeondongName: '수유2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '3',
      sigunguName: '강북구',
      eupmyeondongNum: '6',
      eupmyeondongName: '수유3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '3',
      sigunguName: '강북구',
      eupmyeondongNum: '7',
      eupmyeondongName: '삼양동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '3',
      sigunguName: '강북구',
      eupmyeondongNum: '8',
      eupmyeondongName: '미아동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '3',
      sigunguName: '강북구',
      eupmyeondongNum: '9',
      eupmyeondongName: '송중동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '3',
      sigunguName: '강북구',
      eupmyeondongNum: '10',
      eupmyeondongName: '송천동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '3',
      sigunguName: '강북구',
      eupmyeondongNum: '11',
      eupmyeondongName: '삼각산동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '3',
      sigunguName: '강북구',
      eupmyeondongNum: '12',
      eupmyeondongName: '우이동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '3',
      sigunguName: '강북구',
      eupmyeondongNum: '13',
      eupmyeondongName: '인수동',
    },

    //4. 서울시 강서구 행정동(20)
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '4',
      sigunguName: '강서구',
      eupmyeondongNum: '1',
      eupmyeondongName: '염창동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '4',
      sigunguName: '강서구',
      eupmyeondongNum: '2',
      eupmyeondongName: '등촌1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '4',
      sigunguName: '강서구',
      eupmyeondongNum: '3',
      eupmyeondongName: '등촌2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '4',
      sigunguName: '강서구',
      eupmyeondongNum: '4',
      eupmyeondongName: '등촌3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '4',
      sigunguName: '강서구',
      eupmyeondongNum: '5',
      eupmyeondongName: '화곡본동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '4',
      sigunguName: '강서구',
      eupmyeondongNum: '6',
      eupmyeondongName: '화곡2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '4',
      sigunguName: '강서구',
      eupmyeondongNum: '7',
      eupmyeondongName: '화곡3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '4',
      sigunguName: '강서구',
      eupmyeondongNum: '8',
      eupmyeondongName: '화곡4동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '4',
      sigunguName: '강서구',
      eupmyeondongNum: '9',
      eupmyeondongName: '화곡6동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '4',
      sigunguName: '강서구',
      eupmyeondongNum: '10',
      eupmyeondongName: '화곡8동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '4',
      sigunguName: '강서구',
      eupmyeondongNum: '11',
      eupmyeondongName: '가양1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '4',
      sigunguName: '강서구',
      eupmyeondongNum: '12',
      eupmyeondongName: '가양2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '4',
      sigunguName: '강서구',
      eupmyeondongNum: '13',
      eupmyeondongName: '가양3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '4',
      sigunguName: '강서구',
      eupmyeondongNum: '14',
      eupmyeondongName: '발산1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '4',
      sigunguName: '강서구',
      eupmyeondongNum: '15',
      eupmyeondongName: '공항동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '4',
      sigunguName: '강서구',
      eupmyeondongNum: '16',
      eupmyeondongName: '방화1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '4',
      sigunguName: '강서구',
      eupmyeondongNum: '17',
      eupmyeondongName: '방화2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '4',
      sigunguName: '강서구',
      eupmyeondongNum: '18',
      eupmyeondongName: '방화3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '4',
      sigunguName: '강서구',
      eupmyeondongNum: '19',
      eupmyeondongName: '화곡1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '4',
      sigunguName: '강서구',
      eupmyeondongNum: '20',
      eupmyeondongName: '우장산동',
    },

    //5. 서울시 관악구 행정동(21)
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '5',
      sigunguName: '관악구',
      eupmyeondongNum: '1',
      eupmyeondongName: '보라매동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '5',
      sigunguName: '관악구',
      eupmyeondongNum: '2',
      eupmyeondongName: '청림동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '5',
      sigunguName: '관악구',
      eupmyeondongNum: '3',
      eupmyeondongName: '행운동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '5',
      sigunguName: '관악구',
      eupmyeondongNum: '4',
      eupmyeondongName: '낙성대동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '5',
      sigunguName: '관악구',
      eupmyeondongNum: '5',
      eupmyeondongName: '중앙동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '5',
      sigunguName: '관악구',
      eupmyeondongNum: '6',
      eupmyeondongName: '인헌동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '5',
      sigunguName: '관악구',
      eupmyeondongNum: '7',
      eupmyeondongName: '남현동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '5',
      sigunguName: '관악구',
      eupmyeondongNum: '8',
      eupmyeondongName: '서원동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '5',
      sigunguName: '관악구',
      eupmyeondongNum: '9',
      eupmyeondongName: '신원동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '5',
      sigunguName: '관악구',
      eupmyeondongNum: '10',
      eupmyeondongName: '서림동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '5',
      sigunguName: '관악구',
      eupmyeondongNum: '11',
      eupmyeondongName: '신사동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '5',
      sigunguName: '관악구',
      eupmyeondongNum: '12',
      eupmyeondongName: '신림동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '5',
      sigunguName: '관악구',
      eupmyeondongNum: '13',
      eupmyeondongName: '난향동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '5',
      sigunguName: '관악구',
      eupmyeondongNum: '14',
      eupmyeondongName: '조원동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '5',
      sigunguName: '관악구',
      eupmyeondongNum: '15',
      eupmyeondongName: '대학동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '5',
      sigunguName: '관악구',
      eupmyeondongNum: '16',
      eupmyeondongName: '은천동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '5',
      sigunguName: '관악구',
      eupmyeondongNum: '17',
      eupmyeondongName: '성현동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '5',
      sigunguName: '관악구',
      eupmyeondongNum: '18',
      eupmyeondongName: '청룡동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '5',
      sigunguName: '관악구',
      eupmyeondongNum: '19',
      eupmyeondongName: '난곡동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '5',
      sigunguName: '관악구',
      eupmyeondongNum: '20',
      eupmyeondongName: '삼성동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '5',
      sigunguName: '관악구',
      eupmyeondongNum: '21',
      eupmyeondongName: '미성동',
    },

    //6. 서울시 광진구 행정동(15)
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '6',
      sigunguName: '광진구',
      eupmyeondongNum: '1',
      eupmyeondongName: '화양동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '6',
      sigunguName: '광진구',
      eupmyeondongNum: '2',
      eupmyeondongName: '군자동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '6',
      sigunguName: '광진구',
      eupmyeondongNum: '3',
      eupmyeondongName: '중곡1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '6',
      sigunguName: '광진구',
      eupmyeondongNum: '4',
      eupmyeondongName: '중곡2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '6',
      sigunguName: '광진구',
      eupmyeondongNum: '5',
      eupmyeondongName: '중곡3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '6',
      sigunguName: '광진구',
      eupmyeondongNum: '6',
      eupmyeondongName: '중곡4동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '6',
      sigunguName: '광진구',
      eupmyeondongNum: '7',
      eupmyeondongName: '능동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '6',
      sigunguName: '광진구',
      eupmyeondongNum: '8',
      eupmyeondongName: '구의1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '6',
      sigunguName: '광진구',
      eupmyeondongNum: '9',
      eupmyeondongName: '구의2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '6',
      sigunguName: '광진구',
      eupmyeondongNum: '10',
      eupmyeondongName: '구의3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '6',
      sigunguName: '광진구',
      eupmyeondongNum: '11',
      eupmyeondongName: '광장동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '6',
      sigunguName: '광진구',
      eupmyeondongNum: '12',
      eupmyeondongName: '자양1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '6',
      sigunguName: '광진구',
      eupmyeondongNum: '13',
      eupmyeondongName: '자양2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '6',
      sigunguName: '광진구',
      eupmyeondongNum: '14',
      eupmyeondongName: '자양3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '6',
      sigunguName: '광진구',
      eupmyeondongNum: '15',
      eupmyeondongName: '자양4동',
    },

    //7. 서울시 구로구 행정동(16)
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '7',
      sigunguName: '구로구',
      eupmyeondongNum: '1',
      eupmyeondongName: '신도림동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '7',
      sigunguName: '구로구',
      eupmyeondongNum: '2',
      eupmyeondongName: '구로1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '7',
      sigunguName: '구로구',
      eupmyeondongNum: '3',
      eupmyeondongName: '구로2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '7',
      sigunguName: '구로구',
      eupmyeondongNum: '4',
      eupmyeondongName: '구로3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '7',
      sigunguName: '구로구',
      eupmyeondongNum: '5',
      eupmyeondongName: '구로4동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '7',
      sigunguName: '구로구',
      eupmyeondongNum: '6',
      eupmyeondongName: '구로5동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '7',
      sigunguName: '구로구',
      eupmyeondongNum: '7',
      eupmyeondongName: '고척1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '7',
      sigunguName: '구로구',
      eupmyeondongNum: '8',
      eupmyeondongName: '고척2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '7',
      sigunguName: '구로구',
      eupmyeondongNum: '9',
      eupmyeondongName: '개봉2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '7',
      sigunguName: '구로구',
      eupmyeondongNum: '10',
      eupmyeondongName: '개봉3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '7',
      sigunguName: '구로구',
      eupmyeondongNum: '11',
      eupmyeondongName: '오류1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '7',
      sigunguName: '구로구',
      eupmyeondongNum: '12',
      eupmyeondongName: '오류2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '7',
      sigunguName: '구로구',
      eupmyeondongNum: '13',
      eupmyeondongName: '수궁동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '7',
      sigunguName: '구로구',
      eupmyeondongNum: '14',
      eupmyeondongName: '가리봉동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '7',
      sigunguName: '구로구',
      eupmyeondongNum: '15',
      eupmyeondongName: '개봉1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '7',
      sigunguName: '구로구',
      eupmyeondongNum: '16',
      eupmyeondongName: '항동',
    },

    //8. 서울시 금천구 행정동(10)
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '8',
      sigunguName: '금천구',
      eupmyeondongNum: '1',
      eupmyeondongName: '가산동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '8',
      sigunguName: '금천구',
      eupmyeondongNum: '2',
      eupmyeondongName: '독산1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '8',
      sigunguName: '금천구',
      eupmyeondongNum: '3',
      eupmyeondongName: '독산2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '8',
      sigunguName: '금천구',
      eupmyeondongNum: '4',
      eupmyeondongName: '독산3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '8',
      sigunguName: '금천구',
      eupmyeondongNum: '5',
      eupmyeondongName: '독산4동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '8',
      sigunguName: '금천구',
      eupmyeondongNum: '6',
      eupmyeondongName: '시흥1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '8',
      sigunguName: '금천구',
      eupmyeondongNum: '7',
      eupmyeondongName: '시흥2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '8',
      sigunguName: '금천구',
      eupmyeondongNum: '8',
      eupmyeondongName: '시흥3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '8',
      sigunguName: '금천구',
      eupmyeondongNum: '9',
      eupmyeondongName: '시흥4동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '8',
      sigunguName: '금천구',
      eupmyeondongNum: '10',
      eupmyeondongName: '시흥5동',
    },

    //9. 서울시 노원구 행정동(19)
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '9',
      sigunguName: '노원구',
      eupmyeondongNum: '1',
      eupmyeondongName: '월계1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '9',
      sigunguName: '노원구',
      eupmyeondongNum: '2',
      eupmyeondongName: '월계2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '9',
      sigunguName: '노원구',
      eupmyeondongNum: '3',
      eupmyeondongName: '월계3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '9',
      sigunguName: '노원구',
      eupmyeondongNum: '4',
      eupmyeondongName: '공릉2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '9',
      sigunguName: '노원구',
      eupmyeondongNum: '5',
      eupmyeondongName: '하계1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '9',
      sigunguName: '노원구',
      eupmyeondongNum: '6',
      eupmyeondongName: '하계2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '9',
      sigunguName: '노원구',
      eupmyeondongNum: '7',
      eupmyeondongName: '중계본동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '9',
      sigunguName: '노원구',
      eupmyeondongNum: '8',
      eupmyeondongName: '중계1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '9',
      sigunguName: '노원구',
      eupmyeondongNum: '9',
      eupmyeondongName: '중계4동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '9',
      sigunguName: '노원구',
      eupmyeondongNum: '10',
      eupmyeondongName: '상계1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '9',
      sigunguName: '노원구',
      eupmyeondongNum: '11',
      eupmyeondongName: '상계2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '9',
      sigunguName: '노원구',
      eupmyeondongNum: '12',
      eupmyeondongName: '상계5동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '9',
      sigunguName: '노원구',
      eupmyeondongNum: '13',
      eupmyeondongName: '상계8동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '9',
      sigunguName: '노원구',
      eupmyeondongNum: '14',
      eupmyeondongName: '상계9동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '9',
      sigunguName: '노원구',
      eupmyeondongNum: '15',
      eupmyeondongName: '상계10동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '9',
      sigunguName: '노원구',
      eupmyeondongNum: '16',
      eupmyeondongName: '상계3.4동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '9',
      sigunguName: '노원구',
      eupmyeondongNum: '17',
      eupmyeondongName: '상계6.7동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '9',
      sigunguName: '노원구',
      eupmyeondongNum: '18',
      eupmyeondongName: '중계2.3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '9',
      sigunguName: '노원구',
      eupmyeondongNum: '19',
      eupmyeondongName: '공릉1동',
    },

    //10. 서울시 도봉구 행정동(14)
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '10',
      sigunguName: '도봉구',
      eupmyeondongNum: '1',
      eupmyeondongName: '쌍문1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '10',
      sigunguName: '도봉구',
      eupmyeondongNum: '2',
      eupmyeondongName: '쌍문2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '10',
      sigunguName: '도봉구',
      eupmyeondongNum: '3',
      eupmyeondongName: '쌍문3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '10',
      sigunguName: '도봉구',
      eupmyeondongNum: '4',
      eupmyeondongName: '쌍문4동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '10',
      sigunguName: '도봉구',
      eupmyeondongNum: '5',
      eupmyeondongName: '방학1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '10',
      sigunguName: '도봉구',
      eupmyeondongNum: '6',
      eupmyeondongName: '방학2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '10',
      sigunguName: '도봉구',
      eupmyeondongNum: '7',
      eupmyeondongName: '방학3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '10',
      sigunguName: '도봉구',
      eupmyeondongNum: '8',
      eupmyeondongName: '창1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '10',
      sigunguName: '도봉구',
      eupmyeondongNum: '9',
      eupmyeondongName: '창2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '10',
      sigunguName: '도봉구',
      eupmyeondongNum: '10',
      eupmyeondongName: '창3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '10',
      sigunguName: '도봉구',
      eupmyeondongNum: '11',
      eupmyeondongName: '창4동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '10',
      sigunguName: '도봉구',
      eupmyeondongNum: '12',
      eupmyeondongName: '창5동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '10',
      sigunguName: '도봉구',
      eupmyeondongNum: '13',
      eupmyeondongName: '도봉1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '10',
      sigunguName: '도봉구',
      eupmyeondongNum: '14',
      eupmyeondongName: '도봉2동',
    },

    //11. 서울시 동대문구 행정동(14)
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '11',
      sigunguName: '동대문구',
      eupmyeondongNum: '1',
      eupmyeondongName: '회기동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '11',
      sigunguName: '동대문구',
      eupmyeondongNum: '2',
      eupmyeondongName: '휘경1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '11',
      sigunguName: '동대문구',
      eupmyeondongNum: '3',
      eupmyeondongName: '휘경2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '11',
      sigunguName: '동대문구',
      eupmyeondongNum: '4',
      eupmyeondongName: '청량리동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '11',
      sigunguName: '동대문구',
      eupmyeondongNum: '5',
      eupmyeondongName: '용신동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '11',
      sigunguName: '동대문구',
      eupmyeondongNum: '6',
      eupmyeondongName: '제기동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '11',
      sigunguName: '동대문구',
      eupmyeondongNum: '7',
      eupmyeondongName: '전농1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '11',
      sigunguName: '동대문구',
      eupmyeondongNum: '8',
      eupmyeondongName: '전농2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '11',
      sigunguName: '동대문구',
      eupmyeondongNum: '9',
      eupmyeondongName: '답십리1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '11',
      sigunguName: '동대문구',
      eupmyeondongNum: '10',
      eupmyeondongName: '답십리2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '11',
      sigunguName: '동대문구',
      eupmyeondongNum: '11',
      eupmyeondongName: '장안1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '11',
      sigunguName: '동대문구',
      eupmyeondongNum: '12',
      eupmyeondongName: '장안2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '11',
      sigunguName: '동대문구',
      eupmyeondongNum: '13',
      eupmyeondongName: '이문1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '11',
      sigunguName: '동대문구',
      eupmyeondongNum: '14',
      eupmyeondongName: '이문2동',
    },

    //12. 서울시 동작구 행정동(15)
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '12',
      sigunguName: '동작구',
      eupmyeondongNum: '1',
      eupmyeondongName: '노량진2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '12',
      sigunguName: '동작구',
      eupmyeondongNum: '2',
      eupmyeondongName: '상도1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '12',
      sigunguName: '동작구',
      eupmyeondongNum: '3',
      eupmyeondongName: '상도2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '12',
      sigunguName: '동작구',
      eupmyeondongNum: '4',
      eupmyeondongName: '상도3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '12',
      sigunguName: '동작구',
      eupmyeondongNum: '5',
      eupmyeondongName: '상도4동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '12',
      sigunguName: '동작구',
      eupmyeondongNum: '6',
      eupmyeondongName: '사당1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '12',
      sigunguName: '동작구',
      eupmyeondongNum: '7',
      eupmyeondongName: '사당3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '12',
      sigunguName: '동작구',
      eupmyeondongNum: '8',
      eupmyeondongName: '사당4동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '12',
      sigunguName: '동작구',
      eupmyeondongNum: '9',
      eupmyeondongName: '사당5동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '12',
      sigunguName: '동작구',
      eupmyeondongNum: '10',
      eupmyeondongName: '대방동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '12',
      sigunguName: '동작구',
      eupmyeondongNum: '11',
      eupmyeondongName: '신대방1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '12',
      sigunguName: '동작구',
      eupmyeondongNum: '12',
      eupmyeondongName: '신대방2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '12',
      sigunguName: '동작구',
      eupmyeondongNum: '13',
      eupmyeondongName: '흑석동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '12',
      sigunguName: '동작구',
      eupmyeondongNum: '14',
      eupmyeondongName: '노량진1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '12',
      sigunguName: '동작구',
      eupmyeondongNum: '15',
      eupmyeondongName: '사당2동',
    },

    //13. 서울시 마포구 행정동(16)
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '13',
      sigunguName: '마포구',
      eupmyeondongNum: '1',
      eupmyeondongName: '용강동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '13',
      sigunguName: '마포구',
      eupmyeondongNum: '2',
      eupmyeondongName: '대흥동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '13',
      sigunguName: '마포구',
      eupmyeondongNum: '3',
      eupmyeondongName: '염리동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '13',
      sigunguName: '마포구',
      eupmyeondongNum: '4',
      eupmyeondongName: '신수동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '13',
      sigunguName: '마포구',
      eupmyeondongNum: '5',
      eupmyeondongName: '서교동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '13',
      sigunguName: '마포구',
      eupmyeondongNum: '6',
      eupmyeondongName: '합정동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '13',
      sigunguName: '마포구',
      eupmyeondongNum: '7',
      eupmyeondongName: '망원1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '13',
      sigunguName: '마포구',
      eupmyeondongNum: '8',
      eupmyeondongName: '망원2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '13',
      sigunguName: '마포구',
      eupmyeondongNum: '9',
      eupmyeondongName: '연남동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '13',
      sigunguName: '마포구',
      eupmyeondongNum: '10',
      eupmyeondongName: '성산1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '13',
      sigunguName: '마포구',
      eupmyeondongNum: '11',
      eupmyeondongName: '성산2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '13',
      sigunguName: '마포구',
      eupmyeondongNum: '12',
      eupmyeondongName: '상암동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '13',
      sigunguName: '마포구',
      eupmyeondongNum: '13',
      eupmyeondongName: '도화동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '13',
      sigunguName: '마포구',
      eupmyeondongNum: '14',
      eupmyeondongName: '서강동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '13',
      sigunguName: '마포구',
      eupmyeondongNum: '15',
      eupmyeondongName: '공덕동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '13',
      sigunguName: '마포구',
      eupmyeondongNum: '16',
      eupmyeondongName: '아현동',
    },

    //14. 서울시 서대문구 행정동(14)
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '14',
      sigunguName: '서대문구',
      eupmyeondongNum: '1',
      eupmyeondongName: '천연동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '14',
      sigunguName: '서대문구',
      eupmyeondongNum: '2',
      eupmyeondongName: '홍제1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '14',
      sigunguName: '서대문구',
      eupmyeondongNum: '3',
      eupmyeondongName: '홍제2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '14',
      sigunguName: '서대문구',
      eupmyeondongNum: '4',
      eupmyeondongName: '홍제3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '14',
      sigunguName: '서대문구',
      eupmyeondongNum: '5',
      eupmyeondongName: '홍은1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '14',
      sigunguName: '서대문구',
      eupmyeondongNum: '6',
      eupmyeondongName: '홍은2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '14',
      sigunguName: '서대문구',
      eupmyeondongNum: '7',
      eupmyeondongName: '남가좌1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '14',
      sigunguName: '서대문구',
      eupmyeondongNum: '8',
      eupmyeondongName: '남가좌2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '14',
      sigunguName: '서대문구',
      eupmyeondongNum: '9',
      eupmyeondongName: '북가좌1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '14',
      sigunguName: '서대문구',
      eupmyeondongNum: '10',
      eupmyeondongName: '북가좌2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '14',
      sigunguName: '서대문구',
      eupmyeondongNum: '11',
      eupmyeondongName: '충현동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '14',
      sigunguName: '서대문구',
      eupmyeondongNum: '12',
      eupmyeondongName: '북아현동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '14',
      sigunguName: '서대문구',
      eupmyeondongNum: '13',
      eupmyeondongName: '신촌동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '14',
      sigunguName: '서대문구',
      eupmyeondongNum: '14',
      eupmyeondongName: '연희동',
    },

    //15. 서울시 서초구 행정동(18)
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '15',
      sigunguName: '서초구',
      eupmyeondongNum: '1',
      eupmyeondongName: '서초1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '15',
      sigunguName: '서초구',
      eupmyeondongNum: '2',
      eupmyeondongName: '서초2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '15',
      sigunguName: '서초구',
      eupmyeondongNum: '3',
      eupmyeondongName: '서초3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '15',
      sigunguName: '서초구',
      eupmyeondongNum: '4',
      eupmyeondongName: '서초4동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '15',
      sigunguName: '서초구',
      eupmyeondongNum: '5',
      eupmyeondongName: '잠원동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '15',
      sigunguName: '서초구',
      eupmyeondongNum: '6',
      eupmyeondongName: '반포본동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '15',
      sigunguName: '서초구',
      eupmyeondongNum: '7',
      eupmyeondongName: '반포1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '15',
      sigunguName: '서초구',
      eupmyeondongNum: '8',
      eupmyeondongName: '반포2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '15',
      sigunguName: '서초구',
      eupmyeondongNum: '9',
      eupmyeondongName: '반포3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '15',
      sigunguName: '서초구',
      eupmyeondongNum: '10',
      eupmyeondongName: '반포4동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '15',
      sigunguName: '서초구',
      eupmyeondongNum: '11',
      eupmyeondongName: '방배본동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '15',
      sigunguName: '서초구',
      eupmyeondongNum: '12',
      eupmyeondongName: '방배1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '15',
      sigunguName: '서초구',
      eupmyeondongNum: '13',
      eupmyeondongName: '방배2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '15',
      sigunguName: '서초구',
      eupmyeondongNum: '14',
      eupmyeondongName: '방배3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '15',
      sigunguName: '서초구',
      eupmyeondongNum: '15',
      eupmyeondongName: '방배4동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '15',
      sigunguName: '서초구',
      eupmyeondongNum: '16',
      eupmyeondongName: '양재1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '15',
      sigunguName: '서초구',
      eupmyeondongNum: '17',
      eupmyeondongName: '양재2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '15',
      sigunguName: '서초구',
      eupmyeondongNum: '18',
      eupmyeondongName: '내곡동',
    },

    //16. 서울시 성동구 행정동(17)
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '16',
      sigunguName: '성동구',
      eupmyeondongNum: '1',
      eupmyeondongName: '왕십리2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '16',
      sigunguName: '성동구',
      eupmyeondongNum: '2',
      eupmyeondongName: '마장동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '16',
      sigunguName: '성동구',
      eupmyeondongNum: '3',
      eupmyeondongName: '사근동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '16',
      sigunguName: '성동구',
      eupmyeondongNum: '4',
      eupmyeondongName: '행당1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '16',
      sigunguName: '성동구',
      eupmyeondongNum: '5',
      eupmyeondongName: '행당2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '16',
      sigunguName: '성동구',
      eupmyeondongNum: '6',
      eupmyeondongName: '응봉동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '16',
      sigunguName: '성동구',
      eupmyeondongNum: '7',
      eupmyeondongName: '금호1가동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '16',
      sigunguName: '성동구',
      eupmyeondongNum: '8',
      eupmyeondongName: '금호4가동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '16',
      sigunguName: '성동구',
      eupmyeondongNum: '9',
      eupmyeondongName: '성수1가1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '16',
      sigunguName: '성동구',
      eupmyeondongNum: '10',
      eupmyeondongName: '성수1가2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '16',
      sigunguName: '성동구',
      eupmyeondongNum: '11',
      eupmyeondongName: '성수2가1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '16',
      sigunguName: '성동구',
      eupmyeondongNum: '12',
      eupmyeondongName: '성수2가3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '16',
      sigunguName: '성동구',
      eupmyeondongNum: '13',
      eupmyeondongName: '송정동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '16',
      sigunguName: '성동구',
      eupmyeondongNum: '14',
      eupmyeondongName: '용답동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '16',
      sigunguName: '성동구',
      eupmyeondongNum: '15',
      eupmyeondongName: '왕십리도선동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '16',
      sigunguName: '성동구',
      eupmyeondongNum: '16',
      eupmyeondongName: '금호2.3가동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '16',
      sigunguName: '성동구',
      eupmyeondongNum: '17',
      eupmyeondongName: '옥수동',
    },

    //17. 서울시 성북구 행정동(20)
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '17',
      sigunguName: '성북구',
      eupmyeondongNum: '1',
      eupmyeondongName: '돈암1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '17',
      sigunguName: '성북구',
      eupmyeondongNum: '2',
      eupmyeondongName: '돈암2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '17',
      sigunguName: '성북구',
      eupmyeondongNum: '3',
      eupmyeondongName: '안암동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '17',
      sigunguName: '성북구',
      eupmyeondongNum: '4',
      eupmyeondongName: '보문동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '17',
      sigunguName: '성북구',
      eupmyeondongNum: '5',
      eupmyeondongName: '정릉1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '17',
      sigunguName: '성북구',
      eupmyeondongNum: '6',
      eupmyeondongName: '정릉2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '17',
      sigunguName: '성북구',
      eupmyeondongNum: '7',
      eupmyeondongName: '정릉3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '17',
      sigunguName: '성북구',
      eupmyeondongNum: '8',
      eupmyeondongName: '정릉4동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '17',
      sigunguName: '성북구',
      eupmyeondongNum: '9',
      eupmyeondongName: '길음1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '17',
      sigunguName: '성북구',
      eupmyeondongNum: '10',
      eupmyeondongName: '길음2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '17',
      sigunguName: '성북구',
      eupmyeondongNum: '11',
      eupmyeondongName: '월곡1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '17',
      sigunguName: '성북구',
      eupmyeondongNum: '12',
      eupmyeondongName: '월곡2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '17',
      sigunguName: '성북구',
      eupmyeondongNum: '13',
      eupmyeondongName: '장위1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '17',
      sigunguName: '성북구',
      eupmyeondongNum: '14',
      eupmyeondongName: '장위2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '17',
      sigunguName: '성북구',
      eupmyeondongNum: '15',
      eupmyeondongName: '장위3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '17',
      sigunguName: '성북구',
      eupmyeondongNum: '16',
      eupmyeondongName: '성북동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '17',
      sigunguName: '성북구',
      eupmyeondongNum: '17',
      eupmyeondongName: '삼선동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '17',
      sigunguName: '성북구',
      eupmyeondongNum: '18',
      eupmyeondongName: '동선동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '17',
      sigunguName: '성북구',
      eupmyeondongNum: '19',
      eupmyeondongName: '종암동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '17',
      sigunguName: '성북구',
      eupmyeondongNum: '20',
      eupmyeondongName: '석관동',
    },

    //18. 서울시 송파구 행정동(27)
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '18',
      sigunguName: '송파구',
      eupmyeondongNum: '1',
      eupmyeondongName: '풍납1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '18',
      sigunguName: '송파구',
      eupmyeondongNum: '2',
      eupmyeondongName: '풍납2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '18',
      sigunguName: '송파구',
      eupmyeondongNum: '3',
      eupmyeondongName: '거여1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '18',
      sigunguName: '송파구',
      eupmyeondongNum: '4',
      eupmyeondongName: '거여2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '18',
      sigunguName: '송파구',
      eupmyeondongNum: '5',
      eupmyeondongName: '마천1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '18',
      sigunguName: '송파구',
      eupmyeondongNum: '6',
      eupmyeondongName: '마천2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '18',
      sigunguName: '송파구',
      eupmyeondongNum: '7',
      eupmyeondongName: '방이1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '18',
      sigunguName: '송파구',
      eupmyeondongNum: '8',
      eupmyeondongName: '방이2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '18',
      sigunguName: '송파구',
      eupmyeondongNum: '9',
      eupmyeondongName: '오륜동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '18',
      sigunguName: '송파구',
      eupmyeondongNum: '10',
      eupmyeondongName: '오금동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '18',
      sigunguName: '송파구',
      eupmyeondongNum: '11',
      eupmyeondongName: '송파1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '18',
      sigunguName: '송파구',
      eupmyeondongNum: '12',
      eupmyeondongName: '송파2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '18',
      sigunguName: '송파구',
      eupmyeondongNum: '13',
      eupmyeondongName: '석촌동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '18',
      sigunguName: '송파구',
      eupmyeondongNum: '14',
      eupmyeondongName: '삼전동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '18',
      sigunguName: '송파구',
      eupmyeondongNum: '15',
      eupmyeondongName: '가락본동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '18',
      sigunguName: '송파구',
      eupmyeondongNum: '16',
      eupmyeondongName: '가락1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '18',
      sigunguName: '송파구',
      eupmyeondongNum: '17',
      eupmyeondongName: '가락2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '18',
      sigunguName: '송파구',
      eupmyeondongNum: '18',
      eupmyeondongName: '문정1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '18',
      sigunguName: '송파구',
      eupmyeondongNum: '19',
      eupmyeondongName: '문정2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '18',
      sigunguName: '송파구',
      eupmyeondongNum: '20',
      eupmyeondongName: '장지동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '18',
      sigunguName: '송파구',
      eupmyeondongNum: '21',
      eupmyeondongName: '위례동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '18',
      sigunguName: '송파구',
      eupmyeondongNum: '22',
      eupmyeondongName: '잠실본동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '18',
      sigunguName: '송파구',
      eupmyeondongNum: '23',
      eupmyeondongName: '잠실2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '18',
      sigunguName: '송파구',
      eupmyeondongNum: '24',
      eupmyeondongName: '잠실3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '18',
      sigunguName: '송파구',
      eupmyeondongNum: '25',
      eupmyeondongName: '잠실4동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '18',
      sigunguName: '송파구',
      eupmyeondongNum: '26',
      eupmyeondongName: '잠실6동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '18',
      sigunguName: '송파구',
      eupmyeondongNum: '27',
      eupmyeondongName: '잠실7동',
    },

    //19. 서울시 양천구 행정동(18)
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '19',
      sigunguName: '양천구',
      eupmyeondongNum: '1',
      eupmyeondongName: '목1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '19',
      sigunguName: '양천구',
      eupmyeondongNum: '2',
      eupmyeondongName: '목2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '19',
      sigunguName: '양천구',
      eupmyeondongNum: '3',
      eupmyeondongName: '목3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '19',
      sigunguName: '양천구',
      eupmyeondongNum: '4',
      eupmyeondongName: '목4동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '19',
      sigunguName: '양천구',
      eupmyeondongNum: '5',
      eupmyeondongName: '목5동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '19',
      sigunguName: '양천구',
      eupmyeondongNum: '6',
      eupmyeondongName: '신월1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '19',
      sigunguName: '양천구',
      eupmyeondongNum: '7',
      eupmyeondongName: '신월2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '19',
      sigunguName: '양천구',
      eupmyeondongNum: '8',
      eupmyeondongName: '신월3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '19',
      sigunguName: '양천구',
      eupmyeondongNum: '9',
      eupmyeondongName: '신월4동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '19',
      sigunguName: '양천구',
      eupmyeondongNum: '10',
      eupmyeondongName: '신월5동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '19',
      sigunguName: '양천구',
      eupmyeondongNum: '11',
      eupmyeondongName: '신월6동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '19',
      sigunguName: '양천구',
      eupmyeondongNum: '12',
      eupmyeondongName: '신월7동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '19',
      sigunguName: '양천구',
      eupmyeondongNum: '13',
      eupmyeondongName: '신정1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '19',
      sigunguName: '양천구',
      eupmyeondongNum: '14',
      eupmyeondongName: '신정2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '19',
      sigunguName: '양천구',
      eupmyeondongNum: '15',
      eupmyeondongName: '신정4동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '19',
      sigunguName: '양천구',
      eupmyeondongNum: '16',
      eupmyeondongName: '신정3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '19',
      sigunguName: '양천구',
      eupmyeondongNum: '17',
      eupmyeondongName: '신정6동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '19',
      sigunguName: '양천구',
      eupmyeondongNum: '18',
      eupmyeondongName: '신정7동',
    },

    //20. 서울시 영등포구 행정동(18)
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '20',
      sigunguName: '영등포구',
      eupmyeondongNum: '1',
      eupmyeondongName: '여의동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '20',
      sigunguName: '영등포구',
      eupmyeondongNum: '2',
      eupmyeondongName: '당산1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '20',
      sigunguName: '영등포구',
      eupmyeondongNum: '3',
      eupmyeondongName: '당산2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '20',
      sigunguName: '영등포구',
      eupmyeondongNum: '4',
      eupmyeondongName: '양평1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '20',
      sigunguName: '영등포구',
      eupmyeondongNum: '5',
      eupmyeondongName: '양평2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '20',
      sigunguName: '영등포구',
      eupmyeondongNum: '6',
      eupmyeondongName: '신길1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '20',
      sigunguName: '영등포구',
      eupmyeondongNum: '7',
      eupmyeondongName: '신길3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '20',
      sigunguName: '영등포구',
      eupmyeondongNum: '8',
      eupmyeondongName: '신길4동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '20',
      sigunguName: '영등포구',
      eupmyeondongNum: '9',
      eupmyeondongName: '신길5동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '20',
      sigunguName: '영등포구',
      eupmyeondongNum: '10',
      eupmyeondongName: '신길6동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '20',
      sigunguName: '영등포구',
      eupmyeondongNum: '11',
      eupmyeondongName: '신길7동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '20',
      sigunguName: '영등포구',
      eupmyeondongNum: '12',
      eupmyeondongName: '대림1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '20',
      sigunguName: '영등포구',
      eupmyeondongNum: '13',
      eupmyeondongName: '대림2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '20',
      sigunguName: '영등포구',
      eupmyeondongNum: '14',
      eupmyeondongName: '대림3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '20',
      sigunguName: '영등포구',
      eupmyeondongNum: '15',
      eupmyeondongName: '영등포본동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '20',
      sigunguName: '영등포구',
      eupmyeondongNum: '16',
      eupmyeondongName: '영등포동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '20',
      sigunguName: '영등포구',
      eupmyeondongNum: '17',
      eupmyeondongName: '도림동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '20',
      sigunguName: '영등포구',
      eupmyeondongNum: '18',
      eupmyeondongName: '문래동',
    },

    //21. 서울시 용산구 행정동(16)
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '21',
      sigunguName: '용산구',
      eupmyeondongNum: '1',
      eupmyeondongName: '후암동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '21',
      sigunguName: '용산구',
      eupmyeondongNum: '2',
      eupmyeondongName: '용산2가동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '21',
      sigunguName: '용산구',
      eupmyeondongNum: '3',
      eupmyeondongName: '남영동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '21',
      sigunguName: '용산구',
      eupmyeondongNum: '4',
      eupmyeondongName: '원효로2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '21',
      sigunguName: '용산구',
      eupmyeondongNum: '5',
      eupmyeondongName: '효창동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '21',
      sigunguName: '용산구',
      eupmyeondongNum: '6',
      eupmyeondongName: '용문동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '21',
      sigunguName: '용산구',
      eupmyeondongNum: '7',
      eupmyeondongName: '이촌1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '21',
      sigunguName: '용산구',
      eupmyeondongNum: '8',
      eupmyeondongName: '이촌2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '21',
      sigunguName: '용산구',
      eupmyeondongNum: '9',
      eupmyeondongName: '이태원1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '21',
      sigunguName: '용산구',
      eupmyeondongNum: '10',
      eupmyeondongName: '이태원2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '21',
      sigunguName: '용산구',
      eupmyeondongNum: '11',
      eupmyeondongName: '서빙고동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '21',
      sigunguName: '용산구',
      eupmyeondongNum: '12',
      eupmyeondongName: '보광동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '21',
      sigunguName: '용산구',
      eupmyeondongNum: '13',
      eupmyeondongName: '청파동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '21',
      sigunguName: '용산구',
      eupmyeondongNum: '14',
      eupmyeondongName: '원효로1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '21',
      sigunguName: '용산구',
      eupmyeondongNum: '15',
      eupmyeondongName: '한강로동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '21',
      sigunguName: '용산구',
      eupmyeondongNum: '16',
      eupmyeondongName: '한남동',
    },

    //22. 서울시 은평구 행정동(16)
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '22',
      sigunguName: '은평구',
      eupmyeondongNum: '1',
      eupmyeondongName: '녹번동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '22',
      sigunguName: '은평구',
      eupmyeondongNum: '2',
      eupmyeondongName: '불광1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '22',
      sigunguName: '은평구',
      eupmyeondongNum: '3',
      eupmyeondongName: '갈현1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '22',
      sigunguName: '은평구',
      eupmyeondongNum: '4',
      eupmyeondongName: '갈현2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '22',
      sigunguName: '은평구',
      eupmyeondongNum: '5',
      eupmyeondongName: '구산동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '22',
      sigunguName: '은평구',
      eupmyeondongNum: '6',
      eupmyeondongName: '대조동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '22',
      sigunguName: '은평구',
      eupmyeondongNum: '7',
      eupmyeondongName: '응암1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '22',
      sigunguName: '은평구',
      eupmyeondongNum: '8',
      eupmyeondongName: '응암2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '22',
      sigunguName: '은평구',
      eupmyeondongNum: '9',
      eupmyeondongName: '신사1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '22',
      sigunguName: '은평구',
      eupmyeondongNum: '10',
      eupmyeondongName: '신사2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '22',
      sigunguName: '은평구',
      eupmyeondongNum: '11',
      eupmyeondongName: '증산동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '22',
      sigunguName: '은평구',
      eupmyeondongNum: '12',
      eupmyeondongName: '수색동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '22',
      sigunguName: '은평구',
      eupmyeondongNum: '13',
      eupmyeondongName: '진관동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '22',
      sigunguName: '은평구',
      eupmyeondongNum: '14',
      eupmyeondongName: '불광2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '22',
      sigunguName: '은평구',
      eupmyeondongNum: '15',
      eupmyeondongName: '응암3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '22',
      sigunguName: '은평구',
      eupmyeondongNum: '16',
      eupmyeondongName: '역촌동',
    },

    //23. 서울시 종로구 행정동(17)
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '23',
      sigunguName: '종로구',
      eupmyeondongNum: '1',
      eupmyeondongName: '사직동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '23',
      sigunguName: '종로구',
      eupmyeondongNum: '2',
      eupmyeondongName: '삼청동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '23',
      sigunguName: '종로구',
      eupmyeondongNum: '3',
      eupmyeondongName: '부암동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '23',
      sigunguName: '종로구',
      eupmyeondongNum: '4',
      eupmyeondongName: '평창동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '23',
      sigunguName: '종로구',
      eupmyeondongNum: '5',
      eupmyeondongName: '무악동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '23',
      sigunguName: '종로구',
      eupmyeondongNum: '6',
      eupmyeondongName: '교남동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '23',
      sigunguName: '종로구',
      eupmyeondongNum: '7',
      eupmyeondongName: '가회동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '23',
      sigunguName: '종로구',
      eupmyeondongNum: '8',
      eupmyeondongName: '종로1.2.3.4가동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '23',
      sigunguName: '종로구',
      eupmyeondongNum: '9',
      eupmyeondongName: '종로5.6가동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '23',
      sigunguName: '종로구',
      eupmyeondongNum: '10',
      eupmyeondongName: '이화동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '23',
      sigunguName: '종로구',
      eupmyeondongNum: '11',
      eupmyeondongName: '혜화동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '23',
      sigunguName: '종로구',
      eupmyeondongNum: '12',
      eupmyeondongName: '창신1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '23',
      sigunguName: '종로구',
      eupmyeondongNum: '13',
      eupmyeondongName: '창신2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '23',
      sigunguName: '종로구',
      eupmyeondongNum: '14',
      eupmyeondongName: '창신3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '23',
      sigunguName: '종로구',
      eupmyeondongNum: '15',
      eupmyeondongName: '숭인1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '23',
      sigunguName: '종로구',
      eupmyeondongNum: '16',
      eupmyeondongName: '숭인2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '23',
      sigunguName: '종로구',
      eupmyeondongNum: '17',
      eupmyeondongName: '청운효자동',
    },

    //24. 서울시 중구 행정동(15)
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '24',
      sigunguName: '중구',
      eupmyeondongNum: '1',
      eupmyeondongName: '소공동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '24',
      sigunguName: '중구',
      eupmyeondongNum: '2',
      eupmyeondongName: '회현동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '24',
      sigunguName: '중구',
      eupmyeondongNum: '3',
      eupmyeondongName: '명동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '24',
      sigunguName: '중구',
      eupmyeondongNum: '4',
      eupmyeondongName: '필동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '24',
      sigunguName: '중구',
      eupmyeondongNum: '5',
      eupmyeondongName: '장충동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '24',
      sigunguName: '중구',
      eupmyeondongNum: '6',
      eupmyeondongName: '광희동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '24',
      sigunguName: '중구',
      eupmyeondongNum: '7',
      eupmyeondongName: '을지로동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '24',
      sigunguName: '중구',
      eupmyeondongNum: '8',
      eupmyeondongName: '신당5동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '24',
      sigunguName: '중구',
      eupmyeondongNum: '9',
      eupmyeondongName: '황학동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '24',
      sigunguName: '중구',
      eupmyeondongNum: '10',
      eupmyeondongName: '중림동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '24',
      sigunguName: '중구',
      eupmyeondongNum: '11',
      eupmyeondongName: '신당동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '24',
      sigunguName: '중구',
      eupmyeondongNum: '12',
      eupmyeondongName: '다산동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '24',
      sigunguName: '중구',
      eupmyeondongNum: '13',
      eupmyeondongName: '약수동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '24',
      sigunguName: '중구',
      eupmyeondongNum: '14',
      eupmyeondongName: '청구동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '24',
      sigunguName: '중구',
      eupmyeondongNum: '15',
      eupmyeondongName: '동화동',
    },

    //25. 서울시 중랑구 행정동(16)
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '25',
      sigunguName: '중랑구',
      eupmyeondongNum: '1',
      eupmyeondongName: '면목2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '25',
      sigunguName: '중랑구',
      eupmyeondongNum: '2',
      eupmyeondongName: '면목4동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '25',
      sigunguName: '중랑구',
      eupmyeondongNum: '3',
      eupmyeondongName: '면목5동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '25',
      sigunguName: '중랑구',
      eupmyeondongNum: '4',
      eupmyeondongName: '면목7동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '25',
      sigunguName: '중랑구',
      eupmyeondongNum: '5',
      eupmyeondongName: '상봉1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '25',
      sigunguName: '중랑구',
      eupmyeondongNum: '6',
      eupmyeondongName: '상봉2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '25',
      sigunguName: '중랑구',
      eupmyeondongNum: '7',
      eupmyeondongName: '중화1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '25',
      sigunguName: '중랑구',
      eupmyeondongNum: '8',
      eupmyeondongName: '중화2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '25',
      sigunguName: '중랑구',
      eupmyeondongNum: '9',
      eupmyeondongName: '묵1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '25',
      sigunguName: '중랑구',
      eupmyeondongNum: '10',
      eupmyeondongName: '묵2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '25',
      sigunguName: '중랑구',
      eupmyeondongNum: '11',
      eupmyeondongName: '망우3동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '25',
      sigunguName: '중랑구',
      eupmyeondongNum: '12',
      eupmyeondongName: '신내1동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '25',
      sigunguName: '중랑구',
      eupmyeondongNum: '13',
      eupmyeondongName: '신내2동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '25',
      sigunguName: '중랑구',
      eupmyeondongNum: '14',
      eupmyeondongName: '면목본동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '25',
      sigunguName: '중랑구',
      eupmyeondongNum: '15',
      eupmyeondongName: '면목3.8동',
    },
    {
      sidoNum: '1',
      sidoName: '서울특별시',
      sigunguNum: '25',
      sigunguName: '중랑구',
      eupmyeondongNum: '16',
      eupmyeondongName: '망우본동',
    },
  ],
};

export default hangjungdong;
