export const PATH = {
  LOGIN: '/',
  REDIRECT: '/oauth/redirect/kakao',
  JOIN: '/join',
  FINISHJOIN: '/finishJoin',
  HOME: '/home',
  SEARCH: '/search',
  MY_PAGE: '/my',
  Register_HR: '/register/help-request',
  Register_HS: '/register/help-serve',
  Register_F: '/register/free',
  NOTIFICATION: '/notification',
  Qna_List: '/inquire',
  Qna_Register: '/inquire/register',
  Qna_Detail: '/inquire/:id',
  Posts: '/post/:id',
  Post: '/post',
  Posts_Edit: '/edit/:id',
  MY_ACTIVITY_RECORD: '/my-activity-record',
  MY: '/my',
  MY_EDIT: '/myEdit',
  INQUIRE: '/inquire', //문의기록
  BOOKMARK: '/bookmark', //즐겨찾기
  CATEGORY_SELECT: '/category-select',
  AGENCY_SIGN_IN: '/agency/sign-in',
  AGENCY_SIGN_UP: '/agency/sign-up',
  AGENCY_EDIT: '/agency/edit',
  MY_VOLUNTEER: '/my-volunteer',
  PAYMENT_CERTIFICATION: '/payment-certification',
  INSTANT_ACTIVITY: '/instant-activity',
  DONATION_BOARD_WRITE: '/donation-board-write',
  DONATION_BOARD: '/donation',
  AGENT: '/agent',
  APPLICANT: '/applicant',
};

export const deployHostName = 'http://13.125.249.51';
